### ISSUE TITLE
哥们,请教一下,秘钥在哪里设置呀

### ISSUE THREAD

**Issue by 6616** [JiauZhang/chatchat#1]
有点不会用,可以给讲解一下吗?

**Comment by JiauZhang** [comment]
新的 README 增加了如何设置秘钥部分

**Comment by JiauZhang** [comment]
https://github.com/JiauZhang/chatchat?tab=readme-ov-file#usage

**Comment by 6616** [comment]
哥们 ,你不是一般的快
